name: Build Version

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "The flutter repository branch name"
        default: "stable"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: carterbox/flutter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: flutterVersion=${{ inputs.branch_name }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}-cache:${{ inputs.branch_name }}
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}-cache:${{ inputs.branch_name }},mode=max
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.branch_name }}
