name: Build Version

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "The flutter repository branch name"
        default: "stable"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/flutter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            platform=${{ matrix.platform }}
          tags: |
            ${{ inputs.branch_name }}
            type=sha
            type=ref,event=tag

      - uses: docker/build-push-action@v3
        with:
          build-args: |
            flutterVersion=${{ inputs.branch_name }}
          cache-from: |
            type=gha
            ${{ env.IMAGE_NAME }}:${{ inputs.branch_name }}
            type=registry,ref=${{ env.IMAGE_NAME }}
          context: .
          platforms: |
            ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
