name: Build Version

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "The flutter repository branch name"
        default: "stable"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: carterbox/flutter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:${{ inputs.branch_name }} \
            --build-arg=flutterVersion=${{ inputs.branch_name }} \
            --cache-from=type=registry,ref=${{ env.IMAGE_NAME }}-cache:${{ inputs.branch_name }} \
            --cache-to=type=registry,ref=${{ env.IMAGE_NAME }}-cache:${{ inputs.branch_name }},mode=max \
            --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            .

      - name: Build and push sudo image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}-sudo:${{ inputs.branch_name }} \
            --build-arg=flutterVersion=${{ inputs.branch_name }} \
            --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            -f Dockerfile.sudo \
            .
